version: '3'

services:

  wordpress:
    build: .
    env_file:
      - .env.dev
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8
    command: ["mysqld", "--mysql-native-password=ON"]
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env.dev

  nginx:
    depends_on:
      - wordpress
    image: nginx
    volumes:
      - .:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

volumes:
  db_data:
