version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env.dev

  wordpress:
    container_name: wpeb
    build: .
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    volumes:
      - .:/var/www/html
    env_file:
      - .env.dev


volumes:
  db_data:
